### ISSUE TITLE
gofetch doesnt run after install?

### ISSUE THREAD

**Issue by theGreenJedi** [tr3ss/gofetch#1]
[](url
<img width="459" alt="Screen Shot 2022-07-28 at 10 46 53 AM" src="https://user-images.githubusercontent.com/16416542/181603654-5959b4b0-61d1-43bb-8094-2b190a75c42f.png">
)

**Comment by tr3ss** [comment]
Hello,

Looks like you don't have the `go` environment variables set up :).

Check with ```echo $GOROOT``` and make sure that it's in your `$PATH`.

Something like this:

```bash
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$HOME/.local/bin:$PATH
```

Alternatively you should be able to run it directly from `~/go/bin`.

![image](https://user-images.githubusercontent.com/21034728/181605601-d654fb3c-1b2e-44de-8659-2efc00de15b5.png)

**Comment by Daniyyell** [comment]
check your /root/go/bin/

you can move the gofetch binary to /bin
